# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      checks: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
    # Install Python and Python packages
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Set the Python version you are using

      - name: Install dependencies
        run: |
          pip install -r BE/requirements.txt

      # Start the REST API
      - name: Start REST API
        run: |
          cd BE
          python calculator.py --rest &
          
      - name: Set up PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Start Selenium container
        run: |
          docker run --name selenium -d --add-host host.docker.internal:host-gateway -p 4444:4444 -p 5900:5900 --shm-size="2g" selenium/standalone-chrome:4.2.1-20220531
     
      - name: Run tests
        run: |
          pytest --junit-xml=report.xml

      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v4.3.1
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: /home/runner/work/DevOps/DevOps/report.xml
          include_passed: true

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: /home/runner/work/DevOps/DevOps/report.xml

          
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.REPOSITORY_USERNAME }}
          password: ${{ secrets.LOGIN_CONTAINER_REGISTRY }}
          
      - name: Build Docker image
        run: |
          docker build -t judevops.azurecr.io/leo_balog-calculator:latest ./BE
          
      - name: Push Docker image
        run: |
          docker push judevops.azurecr.io/leo_balog-calculator:latest
